kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: client2-edit
subjects:
- kind: Group
  name: tenant2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: client2-edit
  apiGroup: rbac.authorization.k8s.io
