apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "60Mi"
    - type: "Container" 
      max:
        cpu: "500m"
        memory: "500Mi"
      min:
        cpu: "30m"
        memory: "50Mi"
      default: 
        cpu: "100m"
        memory: "200Mi"
      defaultRequest: 
        cpu: "50m"
        memory: "100Mi"
    - type: "PersistentVolumeClaim" 
      min:
        storage: "100Mi"
      max:
        storage: "2Gi"
