apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-client1
spec:
#  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
           name: client1
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
           name: client1
