apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: 
spec:
  hard:
    requests.cpu: "500m"
    requests. memory: "500Mi"
    limits.cpu: "1"
    limits. memory: "1Gi"
