kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: client1-edit
  namespace: client1
subjects:
- kind: Group
  name: tenant1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: client1-edit
  apiGroup: rbac.authorization.k8s.io
